/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejepracaurlab1;

/**
 *
 * @author norma
 */
public class CrearEmpresa extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearEmpresa
     */
    public CrearEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jDPInterno = new javax.swing.JDesktopPane();
        jTFRaSocial = new javax.swing.JTextField();
        jTFCuit = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLRazSocial = new javax.swing.JLabel();
        jLCuit = new javax.swing.JLabel();

        jLTitulo.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLTitulo.setText("   Ingrese datos");

        jDPInterno.setBackground(new java.awt.Color(153, 102, 255));
        jDPInterno.setForeground(new java.awt.Color(51, 0, 204));

        jButton1.setBackground(new java.awt.Color(102, 0, 153));
        jButton1.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Crear Empresa");

        jLRazSocial.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLRazSocial.setText("Razon social");

        jLCuit.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLCuit.setText("CUIT");

        jDPInterno.setLayer(jTFRaSocial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPInterno.setLayer(jTFCuit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPInterno.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPInterno.setLayer(jLRazSocial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPInterno.setLayer(jLCuit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDPInternoLayout = new javax.swing.GroupLayout(jDPInterno);
        jDPInterno.setLayout(jDPInternoLayout);
        jDPInternoLayout.setHorizontalGroup(
            jDPInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDPInternoLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jDPInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jDPInternoLayout.createSequentialGroup()
                        .addComponent(jLCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDPInternoLayout.createSequentialGroup()
                        .addComponent(jLRazSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFRaSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
            .addGroup(jDPInternoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDPInternoLayout.setVerticalGroup(
            jDPInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDPInternoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jDPInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFRaSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLRazSocial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDPInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCuit))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDPInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(193, 193, 193))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLTitulo)
                .addGap(12, 12, 12)
                .addComponent(jDPInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDPInterno;
    private javax.swing.JLabel jLCuit;
    private javax.swing.JLabel jLRazSocial;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JTextField jTFCuit;
    private javax.swing.JTextField jTFRaSocial;
    // End of variables declaration//GEN-END:variables
}
