/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejepracaurlab1;

import ejepracaurlab1.Modelo.Categoria;
import ejepracaurlab1.Modelo.Empleado;
import javax.swing.JOptionPane;

/**
 *
 * @author norma
 */
public class DatosEmpleado extends javax.swing.JInternalFrame {
 private Empleado emplEncontrodo = null;
    public DatosEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDInterno = new javax.swing.JDesktopPane();
        jLDni = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLCategoria = new javax.swing.JLabel();
        jLSueldo = new javax.swing.JLabel();
        jLEmpresa = new javax.swing.JLabel();
        jBGuardar = new javax.swing.JButton();
        jBBuscarEmp = new javax.swing.JButton();
        jTFDni = new javax.swing.JTextField();
        jTFNombre = new javax.swing.JTextField();
        jTFApellido = new javax.swing.JTextField();
        jTSueldo = new javax.swing.JTextField();
        jCBCategoria = new javax.swing.JComboBox<>();
        jTFEmpresa = new javax.swing.JTextField();
        jBSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jDInterno.setBackground(new java.awt.Color(153, 102, 255));

        jLDni.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLDni.setText("Documento");

        jLNombre.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLNombre.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel4.setText("Apellido");

        jLCategoria.setText("Categoria");

        jLSueldo.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLSueldo.setText("Sueldo");

        jLEmpresa.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLEmpresa.setText("Empresa");

        jBGuardar.setBackground(new java.awt.Color(102, 0, 153));
        jBGuardar.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jBGuardar.setForeground(new java.awt.Color(153, 102, 255));
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBBuscarEmp.setBackground(new java.awt.Color(102, 0, 153));
        jBBuscarEmp.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jBBuscarEmp.setForeground(new java.awt.Color(153, 102, 255));
        jBBuscarEmp.setIcon(new javax.swing.ImageIcon("C:\\Users\\norma\\Documents\\NetBeansProjects\\ejePracAurLab1\\src\\ejepracaurlab1\\Imagen\\icons8-buscar-cliente-80.png")); // NOI18N
        jBBuscarEmp.setText("Mostrar Empleado");
        jBBuscarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarEmpActionPerformed(evt);
            }
        });

        jCBCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new Categoria[] { Categoria.JEFE, Categoria.GERENTE, Categoria.ADMINISTRATIVO, Categoria.OPERARIOPRODUCCION}));

        jBSalir.setBackground(new java.awt.Color(153, 51, 255));
        jBSalir.setForeground(new java.awt.Color(153, 102, 255));
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jDInterno.setLayer(jLDni, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDInterno.setLayer(jLNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDInterno.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDInterno.setLayer(jLCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDInterno.setLayer(jLSueldo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDInterno.setLayer(jLEmpresa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDInterno.setLayer(jBGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDInterno.setLayer(jBBuscarEmp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDInterno.setLayer(jTFDni, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDInterno.setLayer(jTFNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDInterno.setLayer(jTFApellido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDInterno.setLayer(jTSueldo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDInterno.setLayer(jCBCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDInterno.setLayer(jTFEmpresa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDInterno.setLayer(jBSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDInternoLayout = new javax.swing.GroupLayout(jDInterno);
        jDInterno.setLayout(jDInternoLayout);
        jDInternoLayout.setHorizontalGroup(
            jDInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDInternoLayout.createSequentialGroup()
                .addGroup(jDInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDInternoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLDni)
                        .addGap(44, 44, 44)
                        .addComponent(jTFDni, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDInternoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLEmpresa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jLCategoria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLSueldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jDInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNombre)
                            .addComponent(jTFApellido)
                            .addComponent(jTSueldo)
                            .addComponent(jCBCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFEmpresa))))
                .addGap(27, 27, 27)
                .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDInternoLayout.createSequentialGroup()
                .addGap(0, 82, Short.MAX_VALUE)
                .addComponent(jBBuscarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDInternoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBSalir)
                .addGap(17, 17, 17))
        );
        jDInternoLayout.setVerticalGroup(
            jDInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDInternoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jDInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDni)
                    .addComponent(jTFDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jDInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCategoria)
                    .addComponent(jCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jDInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDInternoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jDInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLSueldo)
                            .addComponent(jTSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEmpresa)
                            .addComponent(jTFEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBBuscarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, Short.MAX_VALUE)
                        .addGap(46, 46, 46))
                    .addGroup(jDInternoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jBGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jBSalir)
                .addGap(64, 64, 64))
        );

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel1.setText("Ingrese datos ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jDInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jDInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
       dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        try{   
        int dni= Integer.parseInt(jTFDni.getText());
          String nombre=jTFNombre.getText();
          String apellido=jTFApellido.getText();
          String empresa=jTFEmpresa.getText();
          double sueldo=Double.parseDouble(jTSueldo.getText());
           Categoria puesto= (Categoria)jCBCategoria.getSelectedItem();
           
          Empleado emp = new Empleado(dni, nombre, apellido, sueldo, puesto);
          
          if (nombre.isEmpty()|| apellido.isEmpty()) {
               JOptionPane.showMessageDialog(this,"no debe haber campos en blanco"); 
               return;
            }
          MenuGral.listaEmpleados.add(emp);
          JOptionPane.showMessageDialog(this,"empleado agregado con exito ");
          
        }catch(NumberFormatException nf){
            JOptionPane.showMessageDialog(this,"debe llenar los campos PRECIO, STOCK");
        }
          jTFDni.setText("");
          jTFNombre.setText("");
          jTFApellido.setText("");
          jTFEmpresa.setText("");
          jTSueldo.setText("");
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBBuscarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarEmpActionPerformed
       
    }//GEN-LAST:event_jBBuscarEmpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarEmp;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<Categoria> jCBCategoria;
    private javax.swing.JDesktopPane jDInterno;
    private javax.swing.JLabel jLCategoria;
    private javax.swing.JLabel jLDni;
    private javax.swing.JLabel jLEmpresa;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLSueldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFDni;
    private javax.swing.JTextField jTFEmpresa;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTSueldo;
    // End of variables declaration//GEN-END:variables

   
}
